In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

import scipy.linalg as la

from numpy.linalg import matrix_power


In [37]:
## Log of real value added

n = 4
a = .1


# ## Unconstrained power law distribution
# S = round(np.power(10, pd.DataFrame(np.random.uniform(2, 4, (n, n)))), -2)
# c = round(np.power(10, pd.DataFrame(np.random.uniform(2, 4, (n, 1)))), -2)

sij = 100
ci = 100

### Schematic edge weights
S = pd.DataFrame(np.full((n, n), sij))
c = pd.DataFrame(np.full(n, ci))

# Nw structures

# M is the adjacency matrix
Mi = np.eye(n)
Mo = np.roll(Mi, -n)
Mc = np.full((n, n), 1)
Ms = np.full((n, n), 0); Ms[0, 1:] = 1; Ms[1:, 0] = 1

Si = pd.DataFrame(Mi*S.values)
So = pd.DataFrame(Mo*S.mean().mean())
Sc = pd.DataFrame(Mc*S.values)
Ss = pd.DataFrame(Ms*S.mean().mean())

In [38]:
r = 1.5

# S = Sc
S = Sc
ratio = (S.sum().sum()/c.sum())[0]
S = S * r/ratio

Sc = S

In [39]:
Ss

0      1      2      3
0    0.0  100.0  100.0  100.0
1  100.0    0.0    0.0    0.0
2  100.0    0.0    0.0    0.0
3  100.0    0.0    0.0    0.0

In [40]:
stot = pd.DataFrame(S.sum(1)) + c
R = S.T.div(stot.values).T ####( don't know if it should be trasposed)
I = pd.DataFrame(np.eye(n))
L = la.inv(I - R)

display(S)
display(pd.DataFrame(L).round(3))

0     1     2     3
0  37.5  37.5  37.5  37.5
1  37.5  37.5  37.5  37.5
2  37.5  37.5  37.5  37.5
3  37.5  37.5  37.5  37.5

0      1      2      3
0  1.375  0.375  0.375  0.375
1  0.375  1.375  0.375  0.375
2  0.375  0.375  1.375  0.375
3  0.375  0.375  0.375  1.375

In [41]:

s2c = np.zeros(n); s2c[0] = .2;
s2c = np.diag(s2c)

display(L.dot(s2c))

display(s2c.dot(L.T))

display(L.dot(s2c).dot(L.T))

#
L.dot(s2c).dot(L.T).sum().sum()

array([[0.275, 0.   , 0.   , 0.   ],
       [0.075, 0.   , 0.   , 0.   ],
       [0.075, 0.   , 0.   , 0.   ],
       [0.075, 0.   , 0.   , 0.   ]])

array([[0.275, 0.075, 0.075, 0.075],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ]])

array([[0.378125, 0.103125, 0.103125, 0.103125],
       [0.103125, 0.028125, 0.028125, 0.028125],
       [0.103125, 0.028125, 0.028125, 0.028125],
       [0.103125, 0.028125, 0.028125, 0.028125]])

1.25

In [42]:

s2c = np.zeros(n); s2c[1] = .2;
s2c = np.diag(s2c)

display(L.dot(s2c))

display(s2c.dot(L.T))

display(L.dot(s2c).dot(L.T))

L.dot(s2c).dot(L.T).sum().sum()

array([[0.   , 0.075, 0.   , 0.   ],
       [0.   , 0.275, 0.   , 0.   ],
       [0.   , 0.075, 0.   , 0.   ],
       [0.   , 0.075, 0.   , 0.   ]])

array([[0.   , 0.   , 0.   , 0.   ],
       [0.075, 0.275, 0.075, 0.075],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ]])

array([[0.028125, 0.103125, 0.028125, 0.028125],
       [0.103125, 0.378125, 0.103125, 0.103125],
       [0.028125, 0.103125, 0.028125, 0.028125],
       [0.028125, 0.103125, 0.028125, 0.028125]])

1.25

In [43]:

s2c = np.zeros(n); s2c[0] = .2; s2c[1] = .2;
s2c = np.diag(s2c)

display(L.dot(s2c))

display(s2c.dot(L.T))

display(L.dot(s2c).dot(L.T))

array([[0.275, 0.075, 0.   , 0.   ],
       [0.075, 0.275, 0.   , 0.   ],
       [0.075, 0.075, 0.   , 0.   ],
       [0.075, 0.075, 0.   , 0.   ]])

array([[0.275, 0.075, 0.075, 0.075],
       [0.075, 0.275, 0.075, 0.075],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ]])

array([[0.40625, 0.20625, 0.13125, 0.13125],
       [0.20625, 0.40625, 0.13125, 0.13125],
       [0.13125, 0.13125, 0.05625, 0.05625],
       [0.13125, 0.13125, 0.05625, 0.05625]])

In [44]:
L.dot(s2c).dot(L.T).sum().sum()

2.5000000000000004

In [45]:
## sample size
m = 10000
c_fl = (np.random.normal(0, np.sqrt(.2), size = (n, m)).T*np.array([0, 1, 0, 0])).T
c_fl;


In [46]:
# create the base levels of c
c_ = np.array(m*[c.values.flatten()]).T

## add fluctuations
c_ = c_ + c_fl

pd.DataFrame(c_)

0           1           2           3           4           5     \
0  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
1   99.826966   99.965637  100.478295   99.697432   99.495423  100.757889   
2  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
3  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   

         6           7           8           9     ...       9990        9991  \
0  100.000000  100.000000  100.000000  100.000000  ...  100.00000  100.000000   
1  100.088075  100.777492   99.007535  100.648049  ...  100.07175  100.574664   
2  100.000000  100.000000  100.000000  100.000000  ...  100.00000  100.000000   
3  100.000000  100.000000  100.000000  100.000000  ...  100.00000  100.000000   

         9992        9993        9994        9995        9996        9997  \
0  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
1  100.224305  100.033356   99.684416  100.388061   99.527344  100.687941   
2  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
3  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   

         9998        9999  
0  100.000000  100.000000  
1  100.147051   99.677318  
2  100.000000  100.000000  
3  100.000000  100.000000  

[4 rows x 10000 columns]

In [47]:
## Variance of each of the rows == diagonal of the cov(sales) matrix
L.dot(c_).var(1)

array([0.02857276, 0.3841449 , 0.02857276, 0.02857276])

array([0.51779274, 0.03236205, 0.03236205, 0.03236205])

In [48]:
## Aggregate volatility from Leontieff - cov(c) matrix
L.dot(c_).sum(0).var()

1.2699005104066008

In [49]:
## Actual c covariance matrix
c_.var(1) # its variance must be near the value we designed

s2c = np.zeros(n); s2c[1] = c_.var(1)[1]; 
s2c = np.diag(s2c)
s2c

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.20318408, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [50]:
# Total sales covariance matrix
L.dot(s2c).dot(L.T)

array([[0.02857276, 0.10476679, 0.02857276, 0.02857276],
       [0.10476679, 0.3841449 , 0.10476679, 0.10476679],
       [0.02857276, 0.10476679, 0.02857276, 0.02857276],
       [0.02857276, 0.10476679, 0.02857276, 0.02857276]])

In [28]:
# Total sales covariance matrix
L.dot(s2c).dot(L.T)

array([[0.51779274, 0.12944819, 0.12944819, 0.12944819],
       [0.12944819, 0.03236205, 0.03236205, 0.03236205],
       [0.12944819, 0.03236205, 0.03236205, 0.03236205],
       [0.12944819, 0.03236205, 0.03236205, 0.03236205]])

In [215]:
# Aggregate volatility, sum of covariance matrix
L.dot(s2c).dot(L.T).sum().sum()

1.8352445428893756

In [216]:
# The question would be what is the difference if we do the same thing on a star network

In [ ]:



    print(['Isolated', 'Circular', 'Complete', 'Star'][i])
    
#     Scale Sales to have certain proportion of consumption.

    
    stot = pd.DataFrame(S.sum(1)) + c
    R = S.T.div(stot.values).T ####( don't know if it should be trasposed)
    I = pd.DataFrame(np.eye(n))
    L = la.inv(I - R)
    
    display(S)
    display(pd.DataFrame(L).round(3))
    
    _1pct = .01*np.mean(c)[0] # one percent of mean consumption level.
    
    basis = _1pct*np.eye(n)
    for vector in basis:
        dc = pd.DataFrame(vector)
        dstot = L.dot(c + dc) - L.dot(c) # = L.dot(dc)
        print(sum(dstot))
    
    
    print('***')